site_name: AI for India
site_url: https://pranaykotas.github.io/aiforindia/
theme:
  name: material
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  font:
   text: Alegreya Sans
   code: Roboto Mono

# Plugins

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/pranaykotas
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pranaykotas
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pranaykotas/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page Tree
nav:
  - Home: index.md
  - AI Geopolitics: geopolitics.md
  - AI in Education: education.md
  - AI for Industry: industry.md
  - AI Fundamentals: fundamentals.md


